version: '3.8'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zoo1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: user_service_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - mysql-db

  user-service:
    build: ./user-service
    container_name: user_service
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
      - service-registry
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/user_service_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: root

  wallet-service:
    build: ./wallet-service
    container_name: wallet_service
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - service-registry

  payment-service:
      build: ./payment-service
      container_name: payment_service
      ports:
        - "8083:8083"
      depends_on:
        - mysql-db
        - service-registry

  transaction-service:
      build: ./transaction-service
      container_name: transaction_service
      ports:
        - "8084:8084"
      depends_on:
        - mysql-db
        - service-registry

  notification-service:
    build: ./notification-service
    container_name: notification_service
    ports:
      - "8085:8085"
    depends_on:
      - mysql-db
      - service-registry

  split-bill-service:
    build: ./split-bill-service
    container_name: split_bill_service
    ports:
      - "8086:8086"
    depends_on:
      - mysql-db
      - service-registry

  api-gateway:
      build: ./api-gateway
      container_name: api_gateway
      ports:
        - "3333:3333"
      depends_on:
        - user-service
        - wallet-service
        - payment-service
        - transaction-service
        - notification-service
        - service-registry

volumes:
  mysql_data:
